### PR TITLE
Stop removing all event listeners on close and disconnect

### LINKED ISSUE #638: Calling `close()` removes all event listeners (including "error")
When a SerialPort is closed by calling `close()`, all event listeners are removed (as per the documentation).  This behavior might be undesired.

If one calls `write` on a closed serial port connection without passing a callback to the `write` method, an "error" event is emitted by default.  So, calling `port.write(buf);` on a closed serial port can cause an "error" event to be emitted without an "error" event handler (even if the user created an "error" event handler before the SerialPort was closed).  In this case, the default Node behavior for this is to throw an exception, which could crash the program.

### PR DESCRIPTION
**Pull request by reconbot**
Should address some of #702 and closes #638 and helps https://github.com/rwaldron/johnny-five/issues/1037

### CODE REVIEW

File: lib/serialport.js [hunk 1]
```diff
@@ -410,9 +410,6 @@ SerialPort.prototype.disconnected = function (err) {
     debug('Disconnect completed with an exception: ' + JSON.stringify(e));
   }
 
-  // TODO THIS IS CRAZY TOWN
```
Comment (bcjordan) [inline lib/serialport.js]: 😆
