### PR TITLE
Move listUnix to its own module

### LINKED ISSUE #650: Command failed error on listing ports (udevadm is missing)
Listing ports on Intel Edison Yocto Linux always fails.

Tested Version: 2.0.5/2.0.6

```
var serialp = require("serialport");
serialp.list(function (err, ports) { console.log(err,ports); });
```
This shows the following error message.
```
{ [Error: Command failed: /bin/sh: /sbin/udevadm: No such file or directory
/bin/sh: /sbin/udevadm: No such file or directory
] killed: false, code: 127, signal: null } [ undefined ]
```
However, udevadm does exist there:
```
$ which udevadm
/bin/udevadm
```

### PR DESCRIPTION
**Pull request by reconbot**
- Refactor and fix bugs 
 - Remove the path behind `udevadm` as it’s not always in the same place but it’s so far it is always in the path
 - Tests listUnix, (`pnpId` assumes a lot about `udevadm` =( )
 - Adds `ttyMDF` to the list of serial ports for “High Speed UART device of Intel Medfield platform”

Fixes #650, #651, #634, #697 and #621

### CODE REVIEW

File: lib/list-unix.js [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+
+    // get only serial port names
+    // TODO statSync is bad bad bad
+    for (var i = files.length - 1; i >= 0; i--) {
+      if (
+          (files[i].indexOf('ttyS') === -1 &&
+            files[i].indexOf('ttyACM') === -1 &&
+            files[i].indexOf('ttyUSB') === -1 &&
+            files[i].indexOf('ttyAMA') === -1 &&
+            files[i].indexOf('ttyMFD') === -1) ||
```
Comment (rwaldron) [inline lib/list-unix.js]: `!(/tty(S|A|U)/g).test(files[i])`

File: lib/list-unix.js [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+
+function udev_parser(udev_output) {
+  var as_json = udev_output_to_json(udev_output);
+
+  var pnpId;
+  if (as_json.devlinks) {
+    as_json.devlinks.split(' ').forEach(function(path) {
+      if (path.indexOf('/by-id/') === -1) { return }
+      pnpId = path.substring(path.lastIndexOf('/') + 1);
+    });
```
Comment (reconbot) [inline lib/list-unix.js]: This fixes a bug, there are two "paths" and one of them is `by-id` but they come in different orders sometimes, the `forEach` isn't strictly necessary I suppose

Comment (rwaldron) [inline lib/list-unix.js]: Got it.

File: test/list-unix.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+    'id_model_id=0043\n' +
+    'DEVLINKS=/dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0 /dev/serial/by-id/pci-NATA_Siolynx2_C8T6VI1F-if00-port0\n',
+  'ttyAMA_im_a_programmer':
+    'DEVNAME=/dev/ttyAMA_im_a_programmer\n' +
+    'DEVLINKS=/dev/serial/by-id/pci-NATA_Siolynx2_C8T6VI1F-if00-port0 /dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0\n',
+  'ttyMFD0':
+    'DEVNAME=/dev/ttyMFD0\n' +
+    'id_vendor_id=0x2341\n' +
+    'id_model_id=0x0043\n'
+};
```
Comment (rwaldron) [inline test/list-unix.js]: Great fixtures, but I wonder if you could put these in a file?

File: lib/list-unix.js (hunk 1 above)
Comment (reconbot) [inline lib/list-unix.js]: I know which kernel modules load most of these dev paths, I'm unsure of how many we don't actually want.

File: test/list-unix.js [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+    'id_vendor_id=2341\n' +
+    'id_model_id=0043\n' +
+    'DEVLINKS=/dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0 /dev/serial/by-id/pci-NATA_Siolynx2_C8T6VI1F-if00-port0\n',
+  'ttyAMA_im_a_programmer':
+    'DEVNAME=/dev/ttyAMA_im_a_programmer\n' +
+    'DEVLINKS=/dev/serial/by-id/pci-NATA_Siolynx2_C8T6VI1F-if00-port0 /dev/serial/by-path/pci-0000:00:14.0-usb-0:2:1.0-port0\n',
+  'ttyMFD0':
+    'DEVNAME=/dev/ttyMFD0\n' +
+    'id_vendor_id=0x2341\n' +
+    'id_model_id=0x0043\n'
```
Comment (rwaldron) [inline test/list-unix.js]: Property keys will be uppercased

File: lib/list-unix.js (hunk 1 above)
Comment (reconbot) [inline lib/list-unix.js]: Which is to say I'm happy to keep patching more known good dev paths until we have an answer to that. But I can clean it up with a regex.

File: test/list-unix.js (hunk 4 above)
Comment (rwaldron) [inline test/list-unix.js]: I can't find any examples of hex values for ID_VENDOR_ID and ID_MODEL_ID

File: test_mocks/list-unix.js [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+    },
+    child_process: {
+      exec: function(cmd, cb) {
+        var port = cmd.split(/\/dev\/(.*)\)/)[1];
+        process.nextTick(function() {
+          cb(null, mockPorts[port]);
+        });
+      }
+    }
+  }
```
Comment (rwaldron) [inline test_mocks/list-unix.js]: This project is using sinon, so you can def benefit from using a sinon sandbox for lifecycle managed stubs and spies

File: lib/list-unix.js (hunk 2 above)
Comment (reconbot) [inline lib/list-unix.js]: Nah doing it without an iterative function isn't easier to understand `Array#find` would be the right answer.

File: test_mocks/list-unix.js (hunk 5 above)
Comment (reconbot) [inline test_mocks/list-unix.js]: I agree. This injects at require time not during test time. It would be hard to stub them once the module is loaded.

File: lib/list-unix.js [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+        return callback(null, []);
+      }
+      return callback(err);
+    }
+
+    // get only serial port names
+    // TODO statSync is bad bad bad
+    for (var i = files.length - 1; i >= 0; i--) {
+      if (
+          !(/tty(S|ACM|USB|AMA|MFD)/).test(files[i]) ||
```
Comment (rwaldron) [inline lib/list-unix.js]: That works too ;)

File: lib/list-unix.js [hunk 7]
```diff
@@ -0,0 +1,83 @@
...
+  var udevInfo = {};
+  var lines = output.split('\n');
+  lines.forEach(function(line) {
+    if (!line || line.trim() === '') {
+      return;
+    }
+    var line_parts = line.trim().split('=');
+    var key = line_parts[0].trim().toLowerCase();
+    udevInfo[key] = line_parts[1].trim();
+  });
```
Comment (rwaldron) [inline lib/list-unix.js]: Well in thaaaaaaaaat case: 

```js
var udevInfo = output.split('\n').reduce(function(accum, line) {
  if (!line || line.trim() === '') {
    return accum;
  }
  var parts = line.trim().split('=').map(function(part) {
    return part.trim();
  });

  accum[parts[0].toLowerCase()] = parts[1];

  return accum;
}, {});
```

File: lib/list-unix.js [hunk 8]
```diff
@@ -0,0 +1,83 @@
...
+  }
+
+  var vendorId = udevInfo.id_vendor_id;
+  if (vendorId && vendorId.substring(0, 2) !== '0x') {
+    vendorId = '0x' + vendorId;
+  }
+
+  var productId = udevInfo.id_model_id;
+  if (productId && productId.substring(0, 2) !== '0x') {
+    productId = '0x' + productId;
```
Comment (rwaldron) [inline lib/list-unix.js]: Still haven't seen any examples in all of the docs, tutorials, articles, SO questions, etc. that show these values having `0x` prefix

File: lib/list-unix.js (hunk 7 above)
Comment (reconbot) [inline lib/list-unix.js]: ahh no kidding, that's in node 0.10?!

File: lib/list-unix.js (hunk 8 above)
Comment (reconbot) [inline lib/list-unix.js]: #621 and https://github.com/spark/particle-cli/issues/190#issuecomment-171656487

File: lib/list-unix.js (hunk 7 above)
Comment (rwaldron) [inline lib/list-unix.js]: reduce? Yes.

File: test_mocks/list-unix.js (hunk 5 above)
Comment (rwaldron) [inline test_mocks/list-unix.js]: Disagree. 

- https://github.com/tessel/t2-cli/blob/master/test/unit/deploy.js#L1709-L1724
- https://github.com/tessel/t2-cli/blob/master/test/unit/deploy.js#L1837
- https://github.com/tessel/t2-cli/blob/master/test/unit/deploy.js#L1900-L1918
- https://github.com/tessel/t2-cli/blob/master/test/unit/deploy.js#L1934-L1936
- https://github.com/tessel/t2-cli/blob/master/test/unit/deploy.js#L1944

And tons more

Comment (reconbot) [inline test_mocks/list-unix.js]: Well, you learn something every day. I'm not up for changing it now. I don't think this approach harms anything.

File: lib/list-unix.js (hunk 8 above)
Comment (rwaldron) [inline lib/list-unix.js]: Nice! Also, I remembered something and dug through Tessel 2 code and discovered the same there. 

Why do you think this value is a hex string and not just evaluated to the decimal value?

Comment (reconbot) [inline lib/list-unix.js]: Someone who came before figured that part out, I have no idea if it's true
but I don't want to change the behavior unless it's actually a bug. So far
nobody has filled that it is.
